/**
 * Financial Glossary (v2.7)
 * 
 * Executive-friendly definitions for key financial terms used throughout
 * the hospitality financial modeling application.
 * 
 * This glossary helps users understand the math without looking at the code.
 */

/**
 * Financial term definition (v5.9: Audit & Glossary Logic).
 * 
 * Enhanced with rich metadata for audit traceability and calculation transparency.
 */
export interface FinancialTerm {
  /** The term acronym or name (e.g., "NOI", "DSCR") */
  term: string;
  /** The term acronym (e.g., "NOI", "DSCR", "IRR") */
  acronym: string;
  /** Full name of the term (e.g., "Net Operating Income") */
  meaning: string;
  /** Executive-friendly explanation text */
  explanation: string;
  /** Mathematical representation of the calculation (e.g., "NOI / Debt Service") */
  calculation: string;
  
  // Legacy fields for backward compatibility
  /** @deprecated Use `meaning` instead */
  fullName?: string;
  /** @deprecated Use `explanation` instead */
  definition?: string;
}

/**
 * Financial glossary containing definitions for key terms.
 * 
 * Provides clear, executive-friendly explanations of financial metrics
 * and concepts used in hospitality financial modeling.
 */
export const FINANCIAL_GLOSSARY: Record<string, FinancialTerm> = {
  NOI: {
    term: 'NOI',
    acronym: 'NOI',
    meaning: 'Net Operating Income',
    explanation: 'Net Operating Income represents the total revenue minus operating expenses, before tax and debt service. It is a key metric for evaluating property performance and represents cash flow available to service debt and provide returns to equity investors.',
    calculation: 'NOI = GOP - Undistributed Expenses - Management Fees - Non-Operating Income/Expense - Maintenance Capex',
    fullName: 'Net Operating Income',
    definition: 'Net Operating Income. The total revenue minus operating expenses, before tax and debt.',
  },
  DSCR: {
    term: 'DSCR',
    acronym: 'DSCR',
    meaning: 'Debt Service Coverage Ratio',
    explanation: 'Debt Service Coverage Ratio measures how many times the property\'s net operating income covers its debt service obligations. A DSCR above 1.0x indicates sufficient cash flow to service debt. Lenders typically require minimum DSCR of 1.20x to 1.35x for commercial real estate loans.',
    calculation: 'DSCR = NOI / Debt Service',
    fullName: 'Debt Service Coverage Ratio',
    definition: 'Debt Service Coverage Ratio. How many times your cash flow covers your debt payments.',
  },
  LTV: {
    term: 'LTV',
    acronym: 'LTV',
    meaning: 'Loan to Value',
    explanation: 'Loan to Value ratio represents the percentage of the property\'s total value (initial investment) that is funded by debt. A lower LTV indicates less leverage and lower risk for lenders. Typical commercial real estate LTV ranges from 60% to 80%.',
    calculation: 'LTV = (Total Debt / Initial Investment) × 100%',
    fullName: 'Loan to Value',
    definition: 'Loan to Value. The percentage of the project funded by debt.',
  },
  IRR: {
    term: 'IRR',
    acronym: 'IRR',
    meaning: 'Internal Rate of Return',
    explanation: 'Internal Rate of Return is the annualized effective compounded return rate that makes the net present value of all cash flows equal to zero. IRR represents the discount rate at which the investment breaks even and is a key metric for comparing investment opportunities.',
    calculation: 'IRR = Discount rate where NPV = 0',
    fullName: 'Internal Rate of Return',
    definition: 'Internal Rate of Return. The annualized effective compounded return rate.',
  },
  EQUITY_MULTIPLE: {
    term: 'Equity Multiple',
    acronym: 'MOIC',
    meaning: 'Equity Multiple (Multiple on Invested Capital)',
    explanation: 'Equity Multiple represents the total cash returned divided by total cash invested. A multiple of 2.0x means investors received twice what they invested over the investment period. Unlike IRR, Equity Multiple does not consider the time value of money.',
    calculation: 'Equity Multiple = Total Distributions / Total Contributions',
    fullName: 'Equity Multiple',
    definition: 'Total cash returned divided by total cash invested.',
  },
  NPV: {
    term: 'NPV',
    acronym: 'NPV',
    meaning: 'Net Present Value',
    explanation: 'Net Present Value represents the present value of future cash flows minus the initial investment. NPV accounts for the time value of money by discounting future cash flows. A positive NPV indicates a profitable investment opportunity.',
    calculation: 'NPV = Σ (Cash Flow_t / (1 + r)^t) - Initial Investment',
    fullName: 'Net Present Value',
    definition: 'Net Present Value. The present value of future cash flows minus the initial investment.',
  },
  WACC: {
    term: 'WACC',
    acronym: 'WACC',
    meaning: 'Weighted Average Cost of Capital',
    explanation: 'Weighted Average Cost of Capital represents the average rate of return required by all investors (debt and equity). WACC accounts for the proportion of debt and equity in the capital structure and their respective costs. It is used as the discount rate in DCF valuations for unlevered cash flows.',
    calculation: 'WACC = (Equity % × Cost of Equity) + (Debt % × Cost of Debt × (1 - Tax Rate))',
    fullName: 'Weighted Average Cost of Capital',
    definition: 'Weighted Average Cost of Capital. The average rate of return required by all investors (debt and equity).',
  },
  UFCF: {
    term: 'UFCF',
    acronym: 'UFCF',
    meaning: 'Unlevered Free Cash Flow',
    explanation: 'Unlevered Free Cash Flow represents cash flow available to all investors (debt and equity) before debt service payments. UFCF is calculated as Net Operating Income minus Maintenance Capex minus Change in Working Capital. It is used in DCF valuations to determine enterprise value.',
    calculation: 'UFCF = NOI - Maintenance Capex - Change in Working Capital',
    fullName: 'Unlevered Free Cash Flow',
    definition: 'Unlevered Free Cash Flow. Cash flow available to all investors (debt and equity) before debt service payments, calculated as NOI minus Maintenance CapEx minus Change in Working Capital.',
  },
  LFCF: {
    term: 'LFCF',
    acronym: 'LFCF',
    meaning: 'Levered Free Cash Flow',
    explanation: 'Levered Free Cash Flow represents cash flow available to equity investors after debt service payments (principal and interest). LFCF is calculated as Unlevered Free Cash Flow minus Debt Service and is used to determine equity value and distribution capacity.',
    calculation: 'LFCF = UFCF - Debt Service',
    fullName: 'Levered Free Cash Flow',
    definition: 'Levered Free Cash Flow. Cash flow available to equity investors after debt service payments, calculated as UFCF minus Debt Service (principal and interest payments).',
  },
  PAYBACK_PERIOD: {
    term: 'Payback Period',
    acronym: 'Payback',
    meaning: 'Payback Period',
    explanation: 'Payback Period represents the time required to recover the initial investment from cash flows, measured in years. Shorter payback periods indicate faster capital recovery and lower risk. Payback Period does not account for cash flows beyond the payback point or the time value of money.',
    calculation: 'Payback Period = Years until cumulative cash flows ≥ Initial Investment',
    fullName: 'Payback Period',
    definition: 'The time required to recover the initial investment from cash flows, measured in years. Shorter payback periods indicate faster capital recovery.',
  },
  LOGNORMAL: {
    term: 'LogNormal Distribution',
    acronym: 'LogNormal',
    meaning: 'LogNormal Distribution',
    explanation: 'A probability distribution where the logarithm of the variable is normally distributed. Best for prices/values that cannot be negative, such as stock prices, real estate values, and revenue figures.',
    calculation: 'LogNormal(x) = exp(Normal(μ, σ))',
    fullName: 'LogNormal Distribution',
    definition: 'Best for prices/values that cannot be negative.',
  },
  PERT: {
    term: 'PERT',
    acronym: 'PERT',
    meaning: 'Program Evaluation and Review Technique',
    explanation: 'A three-point estimation technique used in project management and risk analysis. PERT uses optimistic, most likely, and pessimistic estimates to model uncertainty. Best for estimating project costs, timelines, and other bounded estimates.',
    calculation: 'PERT = (Optimistic + 4×Most Likely + Pessimistic) / 6',
    fullName: 'Program Evaluation and Review Technique',
    definition: 'Program Evaluation and Review Technique. Best for estimating project costs/timelines.',
  },
  SENIOR_DSCR: {
    term: 'Senior DSCR',
    acronym: 'Senior DSCR',
    meaning: 'Senior Debt Service Coverage Ratio',
    explanation: 'Debt Service Coverage Ratio calculated using only senior debt service obligations (excluding subordinated/mezzanine debt). Senior DSCR is a key covenant metric for senior lenders and is typically required to be above 1.20x to 1.35x.',
    calculation: 'Senior DSCR = NOI / Senior Debt Service',
    fullName: 'Senior Debt Service Coverage Ratio',
    definition: 'Debt Service Coverage Ratio for Senior Debt only. Key for bank covenants.',
  },
  COMPOUND_PREF: {
    term: 'Compound Pref',
    acronym: 'Compound Pref',
    meaning: 'Compound Preferred Return',
    explanation: 'A preferred return calculation method where unpaid preferred returns compound over time, similar to an interest-bearing account. Unpaid preferred returns are added to the principal balance and earn returns in subsequent periods.',
    calculation: 'Compound Pref = Principal × (1 + Rate)^Periods - Principal',
    fullName: 'Compound Preferred Return',
    definition: 'Preferred return calculated like an interest-bearing account, compounding unpaid balances.',
  },
  S_CURVE: {
    term: 'S-Curve',
    acronym: 'S-Curve',
    meaning: 'S-Curve Construction Spending Pattern',
    explanation: 'A sigmoid-shaped spending pattern for construction projects where spending starts slow (mobilization phase), accelerates rapidly in the middle phase (active construction), and tapers off at completion (finishing phase). The S-curve reflects realistic construction cash flow patterns.',
    calculation: 'S-Curve(t) = Total Budget × Sigmoid(t / Duration)',
    fullName: 'S-Curve Construction Spending Pattern',
    definition: 'A sigmoid-shaped spending pattern for construction projects where spending starts slow, accelerates rapidly in the middle phase, and tapers off at completion.',
  },
  BARTER: {
    term: 'Barter (Permuta)',
    acronym: 'Barter',
    meaning: 'Barter or Permuta (Land Swap)',
    explanation: 'A land acquisition method where land is exchanged for other assets (typically other land parcels) rather than purchased with cash. In financial modeling, barter transactions create positive cash flow entries that offset land acquisition costs, allowing for creative deal structures.',
    calculation: 'Barter Cash Flow = Value of Asset Received - Value of Asset Given',
    fullName: 'Barter or Permuta (Land Swap)',
    definition: 'A land acquisition method where land is exchanged for other assets (typically other land parcels) rather than purchased with cash. In financial modeling, barter transactions create positive cash flow entries that offset land acquisition costs.',
  },
  RAMP_UP: {
    term: 'Ramp-up',
    acronym: 'Ramp-up',
    meaning: 'Operational Ramp-up',
    explanation: 'The gradual increase in operational performance from project launch to full stabilization. Revenue, occupancy, and operational metrics increase over a specified period (typically 12-24 months) rather than starting at 100% capacity. Ramp-up reflects realistic operational startup patterns.',
    calculation: 'Ramp-up(t) = Target × (t / Ramp-up Period)',
    fullName: 'Operational Ramp-up',
    definition: 'The gradual increase in operational performance from project launch to full stabilization. Revenue, occupancy, and operational metrics increase over a specified period (typically 12-24 months) rather than starting at 100% capacity.',
  },
  EQUITY_PEAK: {
    term: 'Equity Peak',
    acronym: 'Equity Peak',
    meaning: 'Peak Equity Requirement',
    explanation: 'The maximum cumulative equity investment required during the project lifecycle, typically occurring during the construction phase. Calculated as the sum of all land acquisition costs plus all construction costs up to the peak spending point. Equity Peak determines the maximum capital commitment required from investors.',
    calculation: 'Equity Peak = max(Cumulative Land Costs + Cumulative Construction Costs)',
    fullName: 'Peak Equity Requirement',
    definition: 'The maximum cumulative equity investment required during the project lifecycle, typically occurring during the construction phase. Calculated as the sum of all land acquisition costs plus all construction costs up to the peak spending point.',
  },
  MOIC: {
    term: 'MOIC',
    acronym: 'MOIC',
    meaning: 'Multiple on Invested Capital',
    explanation: 'Multiple on Invested Capital represents the total cash returned divided by total cash invested. Also known as Equity Multiple. A MOIC of 2.0x means investors received twice what they invested over the investment period. Unlike IRR, MOIC does not consider the time value of money.',
    calculation: 'MOIC = Total Distributions / Total Contributions',
    fullName: 'Multiple on Invested Capital',
    definition: 'Multiple on Invested Capital. The total cash returned divided by total cash invested. Also known as Equity Multiple. A MOIC of 2.0x means you received twice what you invested.',
  },
  GOP: {
    term: 'GOP',
    acronym: 'GOP',
    meaning: 'Gross Operating Profit',
    explanation: 'Gross Operating Profit represents profit after direct operating costs (departmental expenses) but before undistributed expenses, following USALI (Uniform System of Accounts for the Lodging Industry) standards. GOP is calculated as Total Revenue minus Departmental Expenses and is a key indicator of operational efficiency.',
    calculation: 'GOP = Total Revenue - Departmental Expenses',
    fullName: 'Gross Operating Profit',
    definition: 'Gross Operating Profit. Calculated as Total Revenue minus Departmental Expenses, following USALI standards. GOP represents profit after direct operating costs but before undistributed expenses.',
  },
  ADR: {
    term: 'ADR',
    acronym: 'ADR',
    meaning: 'Average Daily Rate',
    explanation: 'The average price paid per room per night, calculated as total room revenue divided by the number of rooms sold. ADR is a key hospitality metric that measures pricing power and revenue per occupied room.',
    calculation: 'ADR = Total Room Revenue / Rooms Sold',
    fullName: 'Average Daily Rate',
    definition: 'Average Daily Rate. The average price paid per room per night, calculated as total room revenue divided by the number of rooms sold.',
  },
  OCCUPANCY: {
    term: 'Occupancy',
    acronym: 'Occupancy',
    meaning: 'Occupancy Rate',
    explanation: 'The percentage of available rooms or units that are occupied during a given period, calculated as rooms sold divided by rooms available. Occupancy rate measures demand and utilization of available inventory.',
    calculation: 'Occupancy = (Rooms Sold / Rooms Available) × 100%',
    fullName: 'Occupancy Rate',
    definition: 'The percentage of available rooms or units that are occupied during a given period, calculated as rooms sold divided by rooms available.',
  },
  REVPAR: {
    term: 'RevPAR',
    acronym: 'RevPAR',
    meaning: 'Revenue per Available Room',
    explanation: 'A key hospitality metric that combines pricing power (ADR) and demand (Occupancy) into a single metric. RevPAR is calculated as ADR multiplied by Occupancy Rate and represents revenue per available room, regardless of whether it is occupied.',
    calculation: 'RevPAR = ADR × Occupancy Rate',
    fullName: 'Revenue per Available Room',
    definition: 'Revenue per Available Room. A key hospitality metric calculated as ADR multiplied by Occupancy Rate, combining pricing power and demand into a single metric.',
  },
  CAPEX: {
    term: 'CapEx',
    acronym: 'CapEx',
    meaning: 'Capital Expenditures',
    explanation: 'Investments in long-term assets such as property, equipment, or improvements. In hospitality, CapEx includes construction costs, major renovations, and replacement reserves. CapEx is deducted from operating income to arrive at free cash flow.',
    calculation: 'CapEx = Construction Costs + Major Renovations + Replacement Reserves',
    fullName: 'Capital Expenditures',
    definition: 'Capital Expenditures. Investments in long-term assets such as property, equipment, or improvements. In hospitality, CapEx includes construction costs, major renovations, and replacement reserves.',
  },
  DCF: {
    term: 'DCF',
    acronym: 'DCF',
    meaning: 'Discounted Cash Flow',
    explanation: 'A valuation method that estimates the value of an investment based on its expected future cash flows, discounted to present value using a discount rate. DCF accounts for the time value of money and is a fundamental valuation technique.',
    calculation: 'DCF Value = Σ (Cash Flow_t / (1 + r)^t)',
    fullName: 'Discounted Cash Flow',
    definition: 'Discounted Cash Flow. A valuation method that estimates the value of an investment based on its expected future cash flows, discounted to present value using a discount rate.',
  },
  VAR: {
    term: 'VaR',
    acronym: 'VaR',
    meaning: 'Value at Risk',
    explanation: 'A statistical risk metric that estimates the maximum potential loss at a given confidence level (typically 95%). VaR answers the question: "What is the worst-case loss we can expect with 95% confidence?"',
    calculation: 'VaR(95%) = Value at 5th percentile of distribution',
    fullName: 'Value at Risk',
    definition: 'Value at Risk. A statistical risk metric that estimates the maximum potential loss at a given confidence level (typically 95%).',
  },
  CVAR: {
    term: 'CVaR',
    acronym: 'CVaR',
    meaning: 'Conditional Value at Risk',
    explanation: 'Also known as Expected Shortfall. CVaR measures the average loss in the worst-case scenarios beyond the VaR threshold. While VaR shows the threshold, CVaR shows the expected loss if that threshold is breached.',
    calculation: 'CVaR = Average of losses beyond VaR threshold',
    fullName: 'Conditional Value at Risk',
    definition: 'Conditional Value at Risk. Also known as Expected Shortfall. CVaR measures the average loss in the worst-case scenarios beyond the VaR threshold.',
  },
  PERCENTILES: {
    term: 'P10/P50/P90',
    acronym: 'P10/P50/P90',
    meaning: 'Percentiles (P10, P50, P90)',
    explanation: 'Statistical percentiles used in risk analysis. P10 represents the 10th percentile (90% of outcomes are better), P50 is the median (50% of outcomes are better), and P90 represents the 90th percentile (10% of outcomes are better).',
    calculation: 'P10 = 10th percentile, P50 = 50th percentile (median), P90 = 90th percentile',
    fullName: 'Percentiles (P10, P50, P90)',
    definition: 'Statistical percentiles used in risk analysis. P10 represents the 10th percentile (90% of outcomes are better), P50 is the median, and P90 represents the 90th percentile (10% of outcomes are better).',
  },
  CATCH_UP: {
    term: 'Catch-up',
    acronym: 'Catch-up',
    meaning: 'Waterfall Catch-up Provision',
    explanation: 'A waterfall mechanism that allows a partner (typically the General Partner) to "catch up" to a target distribution split after preferred returns are satisfied. Distributions are allocated according to the target split until the cumulative distribution ratio matches the target.',
    calculation: 'Catch-up = Distributions until (GP Cumulative / Total Cumulative) = Target GP %',
    fullName: 'Waterfall Catch-up Provision',
    definition: 'A waterfall mechanism that allows a partner (typically the General Partner) to "catch up" to a target distribution split after preferred returns are satisfied. Distributions are allocated according to the target split until the cumulative distribution ratio matches the target.',
  },
  CLAWBACK: {
    term: 'Clawback',
    acronym: 'Clawback',
    meaning: 'Waterfall Clawback Provision',
    explanation: 'A waterfall mechanism that allows Limited Partners to "claw back" excess distributions from General Partners if final returns do not meet certain thresholds. Ensures that GPs do not receive more than their entitled share if the investment underperforms.',
    calculation: 'Clawback = max(0, GP Excess Distributions - GP Entitled Share)',
    fullName: 'Waterfall Clawback Provision',
    definition: 'A waterfall mechanism that allows Limited Partners to "claw back" excess distributions from General Partners if final returns do not meet certain thresholds. Ensures that GPs do not receive more than their entitled share if the investment underperforms.',
  },
  HURDLE: {
    term: 'Hurdle',
    acronym: 'Hurdle',
    meaning: 'Hurdle Rate',
    explanation: 'The minimum rate of return (typically expressed as an IRR) that must be achieved before certain waterfall tiers are activated. Once the hurdle is met, distributions may move to the next tier (e.g., promote).',
    calculation: 'Hurdle = Minimum IRR required before promote tier activates',
    fullName: 'Hurdle Rate',
    definition: 'The minimum rate of return (typically expressed as an IRR) that must be achieved before certain waterfall tiers are activated. Once the hurdle is met, distributions may move to the next tier (e.g., promote).',
  },
  PROMOTE: {
    term: 'Promote',
    acronym: 'Promote',
    meaning: 'Promote or Carried Interest',
    explanation: 'The General Partner\'s share of profits above the preferred return and catch-up provisions. Typically a higher percentage (e.g., 20-30%) of profits after LPs receive their preferred return. Promote aligns GP incentives with investment performance.',
    calculation: 'Promote = (Total Distributions - Preferred Returns - Catch-up) × Promote %',
    fullName: 'Promote or Carried Interest',
    definition: 'The General Partner\'s share of profits above the preferred return and catch-up provisions. Typically a higher percentage (e.g., 20-30%) of profits after LPs receive their preferred return.',
  },
  USALI: {
    term: 'USALI',
    acronym: 'USALI',
    meaning: 'Uniform System of Accounts for the Lodging Industry',
    explanation: 'A standardized accounting framework for hospitality operations that ensures consistent financial reporting across properties. USALI defines revenue categories, expense classifications, and profit metrics (GOP, NOI) used throughout the hospitality industry.',
    calculation: 'USALI Structure: Revenue → GOP → NOI',
    fullName: 'Uniform System of Accounts for the Lodging Industry',
    definition: 'Uniform System of Accounts for the Lodging Industry. A standardized accounting framework for hospitality operations that ensures consistent financial reporting across properties.',
  },
  TERMINAL_GROWTH: {
    term: 'Terminal Growth',
    acronym: 'Terminal Growth',
    meaning: 'Terminal Growth Rate',
    explanation: 'The assumed perpetual growth rate used in DCF valuation to calculate terminal value. Typically ranges from 1-3% and should not exceed the long-term GDP growth rate. Terminal growth captures the value of cash flows beyond the projection period.',
    calculation: 'Terminal Value = Final Year Cash Flow × (1 + g) / (r - g)',
    fullName: 'Terminal Growth Rate',
    definition: 'The assumed perpetual growth rate used in DCF valuation to calculate terminal value. Typically ranges from 1-3% and should not exceed the long-term GDP growth rate.',
  },
  DISCOUNT_RATE: {
    term: 'Discount Rate',
    acronym: 'Discount Rate',
    meaning: 'Discount Rate',
    explanation: 'The rate used to discount future cash flows to present value in DCF calculations. Typically set equal to WACC for unlevered valuations or cost of equity for levered valuations. The discount rate reflects the risk and opportunity cost of capital.',
    calculation: 'Discount Rate = WACC (unlevered) or Cost of Equity (levered)',
    fullName: 'Discount Rate',
    definition: 'The rate used to discount future cash flows to present value in DCF calculations. Typically set equal to WACC for unlevered valuations or cost of equity for levered valuations.',
  },
  DEPARTMENTAL_EXPENSES: {
    term: 'Departmental Expenses',
    acronym: 'Dept Expenses',
    meaning: 'Departmental Expenses (USALI)',
    explanation: 'Direct expenses attributable to revenue-generating departments, following USALI standards. Includes Cost of Goods Sold (COGS) and direct departmental labor. Departmental expenses are subtracted from revenue to calculate Gross Operating Profit (GOP).',
    calculation: 'Departmental Expenses = COGS + Direct Departmental Labor',
    fullName: 'Departmental Expenses (USALI)',
    definition: 'Direct expenses attributable to revenue-generating departments, following USALI standards. Includes Cost of Goods Sold (COGS) and direct departmental labor.',
  },
  UNDISTRIBUTED_EXPENSES: {
    term: 'Undistributed Expenses',
    acronym: 'Undistributed',
    meaning: 'Undistributed Expenses (USALI)',
    explanation: 'Operating expenses not directly attributable to specific revenue-generating departments, following USALI standards. Includes administrative costs, marketing, utilities, insurance, and other overhead expenses. Undistributed expenses are subtracted from GOP to calculate NOI.',
    calculation: 'Undistributed Expenses = Administrative + Marketing + Utilities + Insurance + Other Overhead',
    fullName: 'Undistributed Expenses (USALI)',
    definition: 'Operating expenses not directly attributable to specific revenue-generating departments, following USALI standards. Includes administrative costs, marketing, utilities, insurance, and other overhead expenses.',
  },
  REPLACEMENT_RESERVE: {
    term: 'Replacement Reserve',
    acronym: 'Replacement Reserve',
    meaning: 'Replacement Reserve (Maintenance CapEx)',
    explanation: 'Funds set aside for the replacement of furniture, fixtures, and equipment (FF&E) and major building components. Typically calculated as a percentage of total revenue and deducted from NOI to arrive at free cash flow. Replacement reserves ensure property quality is maintained over time.',
    calculation: 'Replacement Reserve = Total Revenue × Replacement Reserve %',
    fullName: 'Replacement Reserve (Maintenance CapEx)',
    definition: 'Funds set aside for the replacement of furniture, fixtures, and equipment (FF&E) and major building components. Typically calculated as a percentage of total revenue and deducted from NOI to arrive at free cash flow.',
  },
  MANAGEMENT_FEES: {
    term: 'Management Fees',
    acronym: 'Mgmt Fees',
    meaning: 'Management Fees',
    explanation: 'Fees paid to a management company for operating the property. Typically calculated as a percentage of revenue or GOP and deducted from operating income. Management fees compensate the operator for day-to-day property management services.',
    calculation: 'Management Fees = Revenue × Management Fee % (or GOP × Management Fee %)',
    fullName: 'Management Fees',
    definition: 'Fees paid to a management company for operating the property. Typically calculated as a percentage of revenue or GOP and deducted from operating income.',
  },
  REFINANCING: {
    term: 'Refinancing',
    acronym: 'Refinancing',
    meaning: 'Debt Refinancing',
    explanation: 'The process of replacing existing debt with new debt, typically to take advantage of better terms, lower interest rates, or to restructure the capital stack. Transaction costs (exit fees, origination fees) are incurred during refinancing and reduce net proceeds.',
    calculation: 'Refinancing Net Proceeds = New Debt Principal - Exit Fees - Origination Fees',
    fullName: 'Debt Refinancing',
    definition: 'The process of replacing existing debt with new debt, typically to take advantage of better terms, lower interest rates, or to restructure the capital stack. Transaction costs (exit fees, origination fees) are incurred during refinancing.',
  },
  TRANSACTION_COSTS: {
    term: 'Transaction Costs',
    acronym: 'Transaction Costs',
    meaning: 'Transaction Costs',
    explanation: 'Costs incurred during debt or equity transactions, including origination fees, exit fees, and other closing costs. Transaction costs reduce the net proceeds from financing and increase the effective cost of capital.',
    calculation: 'Transaction Costs = Origination Fees + Exit Fees + Closing Costs',
    fullName: 'Transaction Costs',
    definition: 'Costs incurred during debt or equity transactions, including origination fees, exit fees, and other closing costs. Transaction costs reduce the net proceeds from financing and increase the effective cost of capital.',
  },
  EXIT_FEE: {
    term: 'Exit Fee',
    acronym: 'Exit Fee',
    meaning: 'Debt Exit Fee',
    explanation: 'A fee charged when debt is repaid or refinanced before maturity. Typically expressed as a percentage of the principal amount being repaid and deducted from cash flow at the time of refinancing or debt repayment.',
    calculation: 'Exit Fee = Principal Amount × Exit Fee %',
    fullName: 'Debt Exit Fee',
    definition: 'A fee charged when debt is repaid or refinanced before maturity. Typically expressed as a percentage of the principal amount being repaid and deducted from cash flow at the time of refinancing or debt repayment.',
  },
  ORIGINATION_FEE: {
    term: 'Origination Fee',
    acronym: 'Origination Fee',
    meaning: 'Debt Origination Fee',
    explanation: 'A fee charged by lenders when debt is issued. Typically expressed as a percentage of the loan amount, paid at Year 0 (or tranche start year) and reduces the net proceeds available to the borrower.',
    calculation: 'Origination Fee = Loan Amount × Origination Fee %',
    fullName: 'Debt Origination Fee',
    definition: 'A fee charged by lenders when debt is issued. Typically expressed as a percentage of the loan amount, paid at Year 0 (or tranche start year) and reduces the net proceeds available to the borrower.',
  },
  RETURN_OF_CAPITAL: {
    term: 'Return of Capital',
    acronym: 'ROC',
    meaning: 'Return of Capital',
    explanation: 'The first tier in a waterfall structure where distributions are allocated to return investors\' initial capital contributions. Must be fully repaid before preferred returns or promote distributions can begin.',
    calculation: 'Return of Capital = min(Distributions, Total Contributions - Cumulative ROC)',
    fullName: 'Return of Capital',
    definition: 'The first tier in a waterfall structure where distributions are allocated to return investors\' initial capital contributions. Must be fully repaid before preferred returns or promote distributions can begin.',
  },
  PREFERRED_RETURN: {
    term: 'Preferred Return',
    acronym: 'Pref Return',
    meaning: 'Preferred Return',
    explanation: 'A guaranteed return paid to Limited Partners before General Partners receive any promote distributions. Typically expressed as an annual IRR (e.g., 8% preferred return) and must be paid until the hurdle rate is achieved.',
    calculation: 'Preferred Return = Cumulative Contributions × Preferred Return Rate × Years',
    fullName: 'Preferred Return',
    definition: 'A guaranteed return paid to Limited Partners before General Partners receive any promote distributions. Typically expressed as an annual IRR (e.g., 8% preferred return) and must be paid until the hurdle rate is achieved.',
  },
  SENIOR_DEBT: {
    term: 'Senior Debt',
    acronym: 'Senior Debt',
    meaning: 'Senior Debt',
    explanation: 'Debt that has priority over other debt tranches in the capital stack. Senior debt is repaid first and has the lowest risk, resulting in lower interest rates. Senior DSCR is a key covenant metric for senior lenders.',
    calculation: 'Senior Debt = Sum of all senior debt tranches',
    fullName: 'Senior Debt',
    definition: 'Debt that has priority over other debt tranches in the capital stack. Senior debt is repaid first and has the lowest risk, resulting in lower interest rates. Senior DSCR is a key covenant metric for senior lenders.',
  },
  SUBORDINATED_DEBT: {
    term: 'Subordinated Debt',
    acronym: 'Sub Debt',
    meaning: 'Subordinated Debt',
    explanation: 'Debt that ranks below senior debt in the capital stack. Repaid after senior debt and carries higher risk, resulting in higher interest rates. Also known as mezzanine debt.',
    calculation: 'Subordinated Debt = Sum of all subordinated/mezzanine debt tranches',
    fullName: 'Subordinated Debt',
    definition: 'Debt that ranks below senior debt in the capital stack. Repaid after senior debt and carries higher risk, resulting in higher interest rates. Also known as mezzanine debt.',
  },
  AMORTIZATION: {
    term: 'Amortization',
    acronym: 'Amortization',
    meaning: 'Debt Amortization',
    explanation: 'The process of gradually repaying debt principal over time through scheduled payments. Common amortization types include interest-only, straight-line (equal principal payments), and custom schedules.',
    calculation: 'Amortization = Principal Payment per Period',
    fullName: 'Debt Amortization',
    definition: 'The process of gradually repaying debt principal over time through scheduled payments. Common amortization types include interest-only, straight-line (equal principal payments), and custom schedules.',
  },
  WORKING_CAPITAL: {
    term: 'Working Capital',
    acronym: 'WC',
    meaning: 'Working Capital',
    explanation: 'The difference between current assets and current liabilities, representing the capital needed to fund day-to-day operations. In financial modeling, typically calculated as a percentage of revenue and represents the change in working capital from period to period.',
    calculation: 'Working Capital = Current Assets - Current Liabilities',
    fullName: 'Working Capital',
    definition: 'The difference between current assets and current liabilities, representing the capital needed to fund day-to-day operations. In financial modeling, typically calculated as a percentage of revenue.',
  },
};

